version: '3.9'

services:

  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5436:5432

  datamanage:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: postgres
