// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"
	paymentsmodel "server/server/internal/models/work"

	mock "github.com/stretchr/testify/mock"
)

// WorkRepository is an autogenerated mock type for the WorkRepository type
type WorkRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, rec
func (_m *WorkRepository) Create(ctx context.Context, rec *paymentsmodel.CreateWork) error {
	ret := _m.Called(ctx, rec)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *paymentsmodel.CreateWork) error); ok {
		r0 = rf(ctx, rec)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, rec
func (_m *WorkRepository) Delete(ctx context.Context, rec *paymentsmodel.DeleteWork) error {
	ret := _m.Called(ctx, rec)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *paymentsmodel.DeleteWork) error); ok {
		r0 = rf(ctx, rec)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx, rec
func (_m *WorkRepository) GetAll(ctx context.Context, rec *paymentsmodel.GetAllWork) ([]paymentsmodel.Work, error) {
	ret := _m.Called(ctx, rec)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []paymentsmodel.Work
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *paymentsmodel.GetAllWork) ([]paymentsmodel.Work, error)); ok {
		return rf(ctx, rec)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *paymentsmodel.GetAllWork) []paymentsmodel.Work); ok {
		r0 = rf(ctx, rec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]paymentsmodel.Work)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *paymentsmodel.GetAllWork) error); ok {
		r1 = rf(ctx, rec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, rec
func (_m *WorkRepository) Update(ctx context.Context, rec *paymentsmodel.UpdateWork) error {
	ret := _m.Called(ctx, rec)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *paymentsmodel.UpdateWork) error); ok {
		r0 = rf(ctx, rec)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWorkRepository creates a new instance of WorkRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkRepository {
	mock := &WorkRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
